#!/bin/sh
#
# Kruxia Flow Environment Initialization
#
# Run this once before starting Kruxia Flow with docker compose.
# Creates RSA keys and generates secure secrets for the environment.
#
# Usage:
#   ./scripts/init.sh
#
# After running:
#   docker compose --profile deploy up

set -eu

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { printf "${GREEN}[init]${NC} %s\n" "$1"; }
log_warn() { printf "${YELLOW}[init]${NC} %s\n" "$1"; }
log_error() { printf "${RED}[init]${NC} %s\n" "$1" >&2; }

# Generate a cryptographically secure random string
generate_secret() {
    length="${1:-48}"
    openssl rand -base64 "$length" | tr -d '\n/+=' | head -c "$length"
}

# Generate RSA key pair for OAuth
generate_rsa_keys() {
    key_dir="$PROJECT_DIR/dev-keys"

    if [ -f "$key_dir/private.pem" ] && [ -f "$key_dir/public.pem" ]; then
        log_info "RSA keys already exist in dev-keys/"
        return 0
    fi

    log_info "Generating RSA key pair for OAuth..."
    mkdir -p "$key_dir"
    openssl genrsa -out "$key_dir/private.pem" 2048 2>/dev/null
    openssl rsa -in "$key_dir/private.pem" -pubout -out "$key_dir/public.pem" 2>/dev/null
    chmod 600 "$key_dir/private.pem"
    chmod 644 "$key_dir/public.pem"
    log_info "RSA keys generated in dev-keys/"
}

# Initialize .env file with secure secrets
init_env() {
    if [ -f "$PROJECT_DIR/.env" ]; then
        log_info ".env already exists"
        return 0
    fi

    log_info "Generating .env with secure secrets..."

    postgres_password=$(generate_secret 32)
    client_secret=$(generate_secret 48)
    timestamp=$(date '+%Y-%m-%dT%H:%M:%S%z')

    cat > "$PROJECT_DIR/.env" << EOF
# Kruxia Flow Environment Configuration
# Generated by scripts/init.sh on ${timestamp}
#
# WARNING: This file contains secrets. Do not commit to version control.

# Database credentials
POSTGRES_PASSWORD=${postgres_password}

# OAuth client credentials
KRUXIAFLOW_CLIENT_ID=kruxiaflow-local
KRUXIAFLOW_CLIENT_SECRET=${client_secret}

# Logging (info default, use debug for profiling)
KRUXIAFLOW_LOG_LEVEL=info
EOF

    chmod 600 "$PROJECT_DIR/.env"
    log_info ".env created with secure random secrets"
}

main() {
    log_info "Initializing Kruxia Flow environment..."
    echo

    # Generate secrets and keys
    init_env
    generate_rsa_keys

    echo
    log_info "Initialization complete!"
    echo
    echo "Next steps:"
    echo "  1. Review/edit .env if needed"
    echo "  2. Start Kruxia Flow:"
    echo "     docker compose --profile deploy up"
    echo
    echo "Or for development:"
    echo "     ./dev up"
    echo
}

main "$@"
