use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Event for publishing (id and timestamp auto-generated by database)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewWorkflowEvent {
    pub workflow_id: Uuid,
    pub event_type: WorkflowEventType,
    pub activity_key: Option<String>,
    pub payload: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iteration: Option<i32>,
}

/// Event returned from polling (includes database-generated fields)
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct WorkflowEvent {
    pub id: Uuid,
    pub workflow_id: Uuid,
    pub event_type: WorkflowEventType,
    pub activity_key: Option<String>,
    pub payload: serde_json::Value,
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub iteration: Option<i32>,
}

/// Workflow definition structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowDefinition {
    pub id: Uuid,
    pub name: String,
    pub version: String,
    pub activities: Vec<ActivityDefinition>,
}

/// Activity definition in workflow
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityDefinition {
    pub key: String,
    pub worker: String,
    pub activity_name: String,
    pub parameters: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<crate::workflow::ActivitySettings>,
    #[serde(rename = "outputs")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_definitions: Option<Vec<crate::workflow::ActivityOutputDefinition>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<DependencyEdge>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dependency_of: Option<Vec<DependencyEdge>>,
}

/// Dependency edge between activities
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DependencyEdge {
    pub activity_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<String>>,
}

/// Workflow event type enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "workflow_event_type", rename_all = "PascalCase")]
pub enum WorkflowEventType {
    WorkflowCreated,
    WorkflowUpdated,
    ActivityScheduled,
    ActivityWaiting,
    ActivitySignaled,
    ActivityCompleted,
    ActivityFailed,
    WorkflowCompleted,
    WorkflowFailed,
}

impl std::fmt::Display for WorkflowEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkflowEventType::WorkflowCreated => write!(f, "WorkflowCreated"),
            WorkflowEventType::WorkflowUpdated => write!(f, "WorkflowUpdated"),
            WorkflowEventType::ActivityScheduled => write!(f, "ActivityScheduled"),
            WorkflowEventType::ActivityWaiting => write!(f, "ActivityWaiting"),
            WorkflowEventType::ActivitySignaled => write!(f, "ActivitySignaled"),
            WorkflowEventType::ActivityCompleted => write!(f, "ActivityCompleted"),
            WorkflowEventType::ActivityFailed => write!(f, "ActivityFailed"),
            WorkflowEventType::WorkflowCompleted => write!(f, "WorkflowCompleted"),
            WorkflowEventType::WorkflowFailed => write!(f, "WorkflowFailed"),
        }
    }
}

/// Workflow status enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "workflow_status", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum WorkflowStatus {
    Created,
    Running,
    Completed,
    Failed,
    Paused,
}

impl std::fmt::Display for WorkflowStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkflowStatus::Created => write!(f, "created"),
            WorkflowStatus::Running => write!(f, "running"),
            WorkflowStatus::Completed => write!(f, "completed"),
            WorkflowStatus::Failed => write!(f, "failed"),
            WorkflowStatus::Paused => write!(f, "paused"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_workflow_event_type_display() {
        assert_eq!(
            WorkflowEventType::WorkflowCreated.to_string(),
            "WorkflowCreated"
        );
        assert_eq!(
            WorkflowEventType::WorkflowUpdated.to_string(),
            "WorkflowUpdated"
        );
        assert_eq!(
            WorkflowEventType::ActivityScheduled.to_string(),
            "ActivityScheduled"
        );
        assert_eq!(
            WorkflowEventType::ActivityWaiting.to_string(),
            "ActivityWaiting"
        );
        assert_eq!(
            WorkflowEventType::ActivitySignaled.to_string(),
            "ActivitySignaled"
        );
        assert_eq!(
            WorkflowEventType::ActivityCompleted.to_string(),
            "ActivityCompleted"
        );
        assert_eq!(
            WorkflowEventType::ActivityFailed.to_string(),
            "ActivityFailed"
        );
        assert_eq!(
            WorkflowEventType::WorkflowCompleted.to_string(),
            "WorkflowCompleted"
        );
        assert_eq!(
            WorkflowEventType::WorkflowFailed.to_string(),
            "WorkflowFailed"
        );
    }

    #[test]
    fn test_workflow_status_display() {
        assert_eq!(WorkflowStatus::Created.to_string(), "created");
        assert_eq!(WorkflowStatus::Running.to_string(), "running");
        assert_eq!(WorkflowStatus::Completed.to_string(), "completed");
        assert_eq!(WorkflowStatus::Failed.to_string(), "failed");
        assert_eq!(WorkflowStatus::Paused.to_string(), "paused");
    }

    #[test]
    fn test_workflow_event_type_serde_roundtrip() {
        let event_type = WorkflowEventType::ActivityCompleted;
        let json = serde_json::to_string(&event_type).unwrap();
        let deserialized: WorkflowEventType = serde_json::from_str(&json).unwrap();
        assert_eq!(event_type, deserialized);
    }

    #[test]
    fn test_workflow_status_serde_roundtrip() {
        let status = WorkflowStatus::Running;
        let json = serde_json::to_string(&status).unwrap();
        let deserialized: WorkflowStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, deserialized);
    }

    #[test]
    fn test_new_workflow_event_serialization() {
        let event = NewWorkflowEvent {
            workflow_id: Uuid::now_v7(),
            event_type: WorkflowEventType::WorkflowCreated,
            activity_key: None,
            payload: serde_json::json!({"input": "test"}),
            iteration: None,
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("WorkflowCreated"));
        assert!(!json.contains("iteration")); // skip_serializing_if = None
    }

    #[test]
    fn test_new_workflow_event_with_iteration() {
        let event = NewWorkflowEvent {
            workflow_id: Uuid::now_v7(),
            event_type: WorkflowEventType::ActivityCompleted,
            activity_key: Some("step1".to_string()),
            payload: serde_json::json!({}),
            iteration: Some(3),
        };
        let json = serde_json::to_string(&event).unwrap();
        assert!(json.contains("\"iteration\":3"));
    }
}
