use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Event for publishing (id and timestamp auto-generated by database)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NewWorkflowEvent {
    pub workflow_id: Uuid,
    pub event_type: WorkflowEventType,
    pub activity_key: Option<String>,
    pub payload: serde_json::Value,
}

/// Event returned from polling (includes database-generated fields)
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct WorkflowEvent {
    pub id: Uuid,
    pub workflow_id: Uuid,
    pub event_type: WorkflowEventType,
    pub activity_key: Option<String>,
    pub payload: serde_json::Value,
    pub timestamp: DateTime<Utc>,
}

/// Workflow definition structure
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowDefinition {
    pub id: Uuid,
    pub name: String,
    pub version: String,
    pub activities: Vec<ActivityDefinition>,
}

/// Activity definition in workflow
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityDefinition {
    pub key: String,
    pub worker: String,
    pub activity_name: String,
    pub parameters: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<crate::queue::ActivitySettings>,
    #[serde(rename = "outputs")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_definitions: Option<Vec<crate::workflow::ActivityOutputDefinition>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<DependencyEdge>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dependency_of: Option<Vec<DependencyEdge>>,
}

/// Dependency edge between activities
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DependencyEdge {
    pub activity_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<String>>,
}

/// Workflow event type enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "workflow_event_type", rename_all = "PascalCase")]
pub enum WorkflowEventType {
    WorkflowCreated,
    WorkflowUpdated,
    ActivityScheduled,
    ActivityCompleted,
    ActivityFailed,
    WorkflowCompleted,
    WorkflowFailed,
}

impl std::fmt::Display for WorkflowEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkflowEventType::WorkflowCreated => write!(f, "WorkflowCreated"),
            WorkflowEventType::WorkflowUpdated => write!(f, "WorkflowUpdated"),
            WorkflowEventType::ActivityScheduled => write!(f, "ActivityScheduled"),
            WorkflowEventType::ActivityCompleted => write!(f, "ActivityCompleted"),
            WorkflowEventType::ActivityFailed => write!(f, "ActivityFailed"),
            WorkflowEventType::WorkflowCompleted => write!(f, "WorkflowCompleted"),
            WorkflowEventType::WorkflowFailed => write!(f, "WorkflowFailed"),
        }
    }
}

/// Workflow status enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "workflow_status", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum WorkflowStatus {
    Created,
    Running,
    Completed,
    Failed,
    Paused,
}

impl std::fmt::Display for WorkflowStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkflowStatus::Created => write!(f, "created"),
            WorkflowStatus::Running => write!(f, "running"),
            WorkflowStatus::Completed => write!(f, "completed"),
            WorkflowStatus::Failed => write!(f, "failed"),
            WorkflowStatus::Paused => write!(f, "paused"),
        }
    }
}
