name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    name: Rust CI
    uses: ./.github/workflows/rust-ci.yml
    secrets: inherit

  python:
    name: Python SDK CI
    uses: ./.github/workflows/py-ci.yml
    secrets: inherit
